version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: payment-postgres
    environment:
      POSTGRES_DB: PaymentDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network

  mongodb:
    image: mongo:7
    container_name: payment-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - payment-network

  redis:
    image: redis:7-alpine
    container_name: payment-redis
    command: redis-server --requirepass 123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - payment-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - payment-network

  mailhog:
    image: mailhog/mailhog
    container_name: payment-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - payment-network

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data:

networks:
  payment-network:
    driver: bridge
