version: '3.8'

services:
  payment-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=PaymentDB;Username=postgres;Password=123
      - ConnectionStrings__MongoDB=mongodb://root:123@mongo:27017
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - mongodb
      - redis
      - rabbitmq
    networks:
      - payment-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: payment-postgres-prod
    environment:
      POSTGRES_DB: PaymentDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - payment-network
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: payment-mongo-prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - mongo_prod_data:/data/db
    networks:
      - payment-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: payment-redis-prod
    command: redis-server --requirepass 123
    ports:
      - "6379:6379"
    volumes:
      - redis_prod_data:/data
    networks:
      - payment-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-rabbitmq-prod
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_prod_data:/var/lib/rabbitmq
    networks:
      - payment-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: payment-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - payment-api
    networks:
      - payment-network
    restart: unless-stopped

volumes:
  postgres_prod_data:
  mongo_prod_data:
  redis_prod_data:
  rabbitmq_prod_data:

networks:
  payment-network:
    driver: bridge
