version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: identityserver_postgres
    environment:
      POSTGRES_DB: IdentityServer8_Microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-network

  identityserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: identityserver_app
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5001
      - IdentityServer__IssuerUri=https://localhost:5001
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=IdentityServer8_Microservice;Username=postgres;Password=postgres123
    depends_on:
      - postgres
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https:ro
    networks:
      - microservice-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: identityserver_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@microservice.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - microservice-network

volumes:
  postgres_data:

networks:
  microservice-network:
    driver: bridge
