import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    <html dir="rtl" lang="fa">
      <body>{children}</body>
    </html>
  );
}



