import "./globals.css";
import Prefooter from "./components/Footers/Prefooter";
import MainFooter from "./components/Footers/Main";
import PostFooter from "./components/Footers/Postfooter";
import Header from "./components/General/Header/Header";
import BannerHeader from "./components/General/Banner-Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="fa">
      <body>
        <div className="grid grid-cols-1 gap-4">
          <BannerHeader />
          <div className="flex flex-col gap-4">
            <Header />
            <div className="w-full">{children}</div>
          </div>
        </div>

        <footer>
          <MainFooter />
          <PostFooter />
        </footer>
      </body>
    </html>
  );
}
