version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: discount-postgres
    environment:
      POSTGRES_DB: DiscountServiceDb_Dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - discount-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: discount-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - discount-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: discount-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - discount-network

  # Discount Service API
  discount-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discount-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=DiscountServiceDb_Dev;Username=postgres;Password=dev_password
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMQ=rabbitmq://guest:guest@rabbitmq:5672/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - discount-network
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  discount-network:
    driver: bridge
