# Override for development environment
version: '3.8'

services:
  cart-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
    volumes:
      - ./CartService.API:/app/source
    ports:
      - "5000:80"
      - "5001:443"

  redis:
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru

  postgres:
    environment:
      - POSTGRES_DB=cart_hangfire_dev
