import { library } from "@fortawesome/fontawesome-svg-core";
import {
  fas,
  faShoppingCart,
  faGauge,
  faBox,
  faPlus,
  faCogs,
  faHistory,
  faBan,
  faTruck,
  faCheck,
  faComment,
  faBell,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faUser,
  faUsers,
  faEdit,
  faTrash,
  faSearch,
  faEnvelope,
  faLock,
  faUnlock,
  faEye,
  faEyeSlash,
  faHome,
  faInfo,
  faExclamation,
  faTimes,
  faSave,
  faUpload,
  faDownload,
  faFile,
  faFileAlt,
  faCalendar,
  faStar,
  faHeart,
  faPhone,
  faMapMarker,
  faCamera,
  faImage,
  faPrint,
  faClipboard,
  faChartBar,
  faChartPie,
  faChartLine,
  faWrench,
  faCog,
  faSync,
  faSpinner,
  faQuestion,
  faChartSimple,
  faCirclePlus,
  faBoxOpen,
  faTags,
  faFolder,
  faCopyright,
  faList,
  faCartShopping,
  faCartPlus,
  faClock,
  faCircleCheck,
  faLocationDot,
  faStore,
  faHandshake,
  faWallet,
  faUserPlus,
  faMedal,
  faUserClock,
  faPercent,
  faBullhorn,
  faGift,
  faPercentage,
  faTicket,
  faEnvelopeOpen,
  faMoneyBill,
  faFileInvoiceDollar,
  faHandHoldingDollar,
  faMoneyCheck,
  faCreditCard,
  faRightLeft,
  faMoneyBillTransfer,
  faNewspaper,
  faSliders,
  faBars,
  faWindowRestore,
  faComments,
  faMessage,
  faUserTag,
  faShuffle,
  faDatabase,
  faSitemap,
  faFloppyDisk,
  faStoreAlt,
  faBagShopping,
  faUsersGear,
  faPlug,
  faShieldHalved,
  faUserSlash,
  faTriangleExclamation,
  faClockRotateLeft,
  faClipboardList,
  faBook,
  faHeadset,
  faVideo,
  faRightFromBracket,
  faCircleQuestion,
  faWarehouse,
  faBoxes,
} from "@fortawesome/free-solid-svg-icons";

  
// افزودن تمام آیکونهای solid به کتابخانه
library.add(fas);

const iconMap = {
  gauge: faGauge,
  box: faBox,
  plus: faPlus,
  cogs: faCogs,
  shoppingCart: faShoppingCart,
  history: faHistory,
  ban: faBan,
  truck: faTruck,
  check: faCheck,
  comment: faComment,
  bell: faBell,
  chevronUp: faChevronUp,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  user: faUser,
  users: faUsers,
  edit: faEdit,
  trash: faTrash,
  search: faSearch,
  envelope: faEnvelope,
  lock: faLock,
  unlock: faUnlock,
  eye: faEye,
  eyeSlash: faEyeSlash,
  home: faHome,
  info: faInfo,
  exclamation: faExclamation,
  times: faTimes,
  save: faSave,
  upload: faUpload,
  download: faDownload,
  file: faFile,
  fileAlt: faFileAlt,
  calendar: faCalendar,
  star: faStar,
  heart: faHeart,
  phone: faPhone,
  mapMarker: faMapMarker,
  camera: faCamera,
  image: faImage,
  print: faPrint,
  clipboard: faClipboard,
  chartBar: faChartBar,
  chartPie: faChartPie,
  chartLine: faChartLine,
  wrench: faWrench,
  cog: faCog,
  sync: faSync,
  spinner: faSpinner,
  question: faQuestion,
  chartSimple: faChartSimple,
  circlePlus: faCirclePlus,
  boxOpen: faBoxOpen,
  tags: faTags,
  folder: faFolder,
  copyright: faCopyright,
  list: faList,
  cartShopping: faCartShopping,
  cartPlus: faCartPlus,
  clock: faClock,
  circleCheck: faCircleCheck,
  locationDot: faLocationDot,
  store: faStore,
  handshake: faHandshake,
  wallet: faWallet,
  userPlus: faUserPlus,
  medal: faMedal,
  userClock: faUserClock,
  percent: faPercent,
  bullhorn: faBullhorn,
  gift: faGift,
  percentage: faPercentage,
  ticket: faTicket,
  envelopeOpen: faEnvelopeOpen,
  moneyBill: faMoneyBill,
  fileInvoiceDollar: faFileInvoiceDollar,
  handHoldingDollar: faHandHoldingDollar,
  moneyCheck: faMoneyCheck,
  creditCard: faCreditCard,
  rightLeft: faRightLeft,
  moneyBillTransfer: faMoneyBillTransfer,
  newspaper: faNewspaper,
  sliders: faSliders,
  bars: faBars,
  windowRestore: faWindowRestore,
  comments: faComments,
  message: faMessage,
  userTag: faUserTag,
  shuffle: faShuffle,
  database: faDatabase,
  sitemap: faSitemap,
  floppyDisk: faFloppyDisk,
  storeAlt: faStoreAlt,
  bagShopping: faBagShopping,
  usersGear: faUsersGear,
  plug: faPlug,
  shieldHalved: faShieldHalved,
  userSlash: faUserSlash,
  triangleExclamation: faTriangleExclamation,
  clockRotateLeft: faClockRotateLeft,
  clipboardList: faClipboardList,
  book: faBook,
  headset: faHeadset,
  video: faVideo,
  rightFromBracket: faRightFromBracket,
  circleQuestion: faCircleQuestion,
  warehouse: faWarehouse,
  boxes: faBoxes,
  boxOpen: faBoxOpen
};

export const getIcon = (iconName) =>
  iconMap[iconName] ? iconMap[iconName] : iconMap.question;
